import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
await p.goto("http://127.0.0.1:3199/v2/index.html", { waitUntil: "networkidle" });
await p.waitForTimeout(500);
await p.evaluate(() => document.querySelector('[data-fd-view="land"] a[href="#"]').click());
await p.waitForTimeout(300);
await p.evaluate(() => document.querySelector('button[title="Registry"]').click());
await p.waitForTimeout(600);
const dbg = await p.evaluate(() => document.getElementById("dc-root").innerText.slice(0,200));
console.log("SCREEN:", JSON.stringify(dbg));
const before = await p.evaluate(() => document.body.innerText.slice(0,0) || document.getElementById("dc-root").innerHTML.includes("LC-constantin-train-78"));
await p.evaluate(() => window.FD.setData("regData", [{ id: "z1", s: "PARITY-PROBE-ROW", g: "g", tk: "t", st: "active", active: "now", model: "m" }]));
await p.waitForTimeout(300);
const after = await p.evaluate(() => document.getElementById("dc-root").innerHTML.includes("PARITY-PROBE-ROW"));
const gone = await p.evaluate(() => !document.getElementById("dc-root").innerHTML.includes("LC-constantin-train-78"));
console.log(JSON.stringify({ seedRenderedBefore: before, newDataRendered: after, oldDataGone: gone }));
await b.close();
